boltlabs-inc/tss-ecdsa

Cargo.toml, src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/messages.rs, src/presign/participant.rs, src/protocol.rs, src/utils.rs
This PR changes the organization of the presign module to be in line with the other modules (the same changes as in pull #3).
1) It makes all of the functions parameterized by an external rng, rather than sampling its own
2) It reorganizes process_messages() to be a simple message sorting function and moves any more complicated logic to other functions.
3) It changes round handling function names to match those in other protocols
It also addresses the clippy issues so that CI can pass
=> Refactor presign (and pass CI)

dev/flame.py, src/auxinfo/participant.rs, src/keygen/participant.rs, src/presign/participant.rs, stats/README.md
This PR adds marks to many of the main functions that get executed in various protocols so that they will appear in flamegraphs. Running `cargo +nightly test --release --features flame_it --package tss-ecdsa --lib -- protocol::tests::test_run_protocol --exact --nocapture` will produce a flamegraph in stats/flame-graph.html
This flamegraph orders functions chronologically on the x axis, but if the same function is called in multiple places in the general execution flow, then it will appear broken up into various chunks, making it hard to tell how much of the overall execution is attributable to that function. 
To address this I wrote a python script (dev/flame.py) which reorganizes the flamegraph (it expects a file named flame-graph.html to be found in the same directory as it) in order to …
=> Benchmarking

examples/network/server.rs, src/auxinfo/participant.rs, src/broadcast/data.rs, src/broadcast/participant.rs, src/errors.rs, src/keygen/participant.rs, src/message_queue.rs, src/messages.rs, src/participant.rs, src/presign/participant.rs, src/presign/round_one.rs, src/presign/round_three.rs, src/presign/round_two.rs, src/protocol.rs, src/storage.rs
This PR addresses issues #11 and #5 
Adding support for broadcasting to Presign ended up being a bit more complicated than I was anticipating. Round one of the protocol (Figure 7) contains sending unique messages to each party and a broadcast (all recipients interact to ensure they all received the same message), and so I split up round one into these two portions. RoundOnePublic is the non-broadcast portion and RoundOnePublicBroadcast deals with the broadcasted portion. 
In order to deal with the added complexity of handling two types of round one messages at the same time, I ended up adding the Participant trait to Presign, allowing it to stash messages and retrieve them later. I also extended the functionality of the Participant trait to allow retrieving only messages from a given …
=> Add Broadcasting and Out-of-Order message handling to Presign 

Cargo.toml, src/auxinfo/participant.rs, src/keygen/participant.rs, src/utils.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pilog.rs, src/zkp/pimod.rs, src/zkp/piprm.rs, src/zkp/setup.rs
Addresses #8, makes progress towards #24.
This PR replaces calls to `BigNumber::random` (which does not take an rng) to `BigNumber::from_rng` (which does). Doing so requires updating the `unknown_order` package which is re-exported through `libpaillier`, so that must be updated as well. As `libpaillier` changed its default backend for `unknown_order` to openssl, a feature flag was added to revert it to continue using the rust `num_bigint` library as a backend instead, for ease of compilation. It also appears that glass_pumpkin no longer needs to be pinned to an old version.
=> Replace calls of BigNumber::random() with BigNumber::from_rng()

src/auxinfo/participant.rs, src/errors.rs, src/keygen/participant.rs, src/paillier.rs, src/presign/participant.rs, src/presign/record.rs, src/protocol.rs, src/utils.rs, src/zkp/piaffg.rs, src/zkp/pilog.rs, src/zkp/pisch.rs
This PR addresses the `unwrap() `removal portion of #13 by replacing unwraps in the main library with errors.
It does not attempt to remove unwraps from tests, nor does it touch any of the example programs
=> Remove unwrap() from main library

src/auxinfo/participant.rs, src/safe_primes_512.rs, src/utils.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pifac.rs, src/zkp/pilog.rs, src/zkp/pimod.rs, src/zkp/piprm.rs, src/zkp/setup.rs
Currently, safe primes are read from a pregenerated file so that tests will be faster (as generating safe primes is expensive). However, as we do not want to do this in production, this PR changes the code so that release builds will sample safe primes on the fly.
If this PR is successful, it will close #36 and make progress towards #29 as it rewrites the internal safe prime generation function to always take an rng.
This can also be considered a prerequisite for #34 to be successful, as safe prime sampling is significant enough to affect end to end benchmark timings.
=> Patch to sample safe primes in release builds

Cargo.toml, src/utils.rs, src/zkp/pifac.rs
Fixes #68
Unused dependency is `integer-encoding`. Unused dev dependencies are `bytes` and `futures`.
Also alphabetizes the toml file and fixes Clippy errors from the latest Rust update.
=> remove unused dependencies #68

src/auxinfo/participant.rs, src/errors.rs, src/paillier.rs, src/presign/participant.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pilog.rs
Fixes #60 
- Adds generation method in the Paillier module to create a decryption key and derive an encryption key
- Removes all direct calls to `libpaillier` constructors outside of the `paillier` module
- Adds an error enum to the paillier module. I decided not to try to fix the big `InternalError` enum at this point -- will leave that to #58. I just moved the Paillier-specific errors into this module and wrote a manual conversion into `InternalError`.
I was hoping to remove all direct access to the `libpaillier` types, but I found a few places where they're accessed to do homomorphic operations. Made #64 to address that.
=> Move libpaillier keys into paillier module

src/auxinfo/participant.rs, src/errors.rs, src/paillier.rs, src/utils.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pifac.rs, src/zkp/pilog.rs, src/zkp/pimod.rs, src/zkp/piprm.rs, src/zkp/setup.rs
Fixes #56 
This PR ballooned a little bit. In #60, I made an API for key generation that takes primes as parameters. However, I realized here that 
1. we never create a new Paillier key from primes that we didn't just generate, and
2. we never generate primes that aren't used in Paillier keys (outside of tests).
So, I decided to move all the prime generation methods into a mini-module within the Paillier module, and to update the key generation API to just take an RNG and generate the primes internally. It now also returns the prime factors, since they're not directly retrievable from the decryption key but we need them in subsequent operations.
The prime generation module didn't change functionally; I cleaned up some documentation and consolidated function calls a little bit.
The prime …
=> Fix key-size bug

.github/workflows/ignored_tests.yml, .github/workflows/main.yml, src/auxinfo/participant.rs, src/keygen/participant.rs
Address #65
This PR actually shouldn't run the new CI, since it's only run on _push_ to main, not PR. So if it looks good, I will push and iterate if it doesn't work as expected.
The best news is, a local run of `cargo make ci` only takes ~1min on my machine now!
=> add github workflow to run slow tests separately

src/errors.rs, src/zkp/pimod.rs
Fix #24 
I'm pretty sure @tyurek already fixed this bug when he fixed the "two primes drawn from a list must be different" bug. To add confidence, I added some extra checks about coprimality in the happy test, and added two tests to look at specific failure cases based on the assumptions of the CRT.
Also improved docs on the CRT function and added another error.
=> Fix Chinese remainder theorem bug

src/paillier.rs, src/presign/participant.rs, src/utils.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pilog.rs
Fix #41 
This adds error handling and, uh, correctness to drawing elements from `ZStar` (not a real type yet). 
Future design thought: The coprimality test we have now works for any modulus `N`, but we only call this function on Paillier encryption keys. Once all the ZKPs have encryption keys typed everywhere (instead of plain `BigNumber`s), we could change this function signature to take `n: PaillierEncryptionKey`. It would fit our use case but isn't required for the general definition.
=> Fix error handling when drawing random ZStar

src/parameters.rs, src/zkp/piprm.rs
Fixes #73
This PR updates the soundness parameter from 8 to 80. 
This caused a small issue with `PiPrm`, which previously held its arrays of values in fixed-length arrays. I found that serde's derivable `Deserialize` can [only handle tuples up to length 32](https://docs.rs/serde/latest/serde/trait.Deserialize.html#impl-Deserialize%3C%27de%3E-for-%5BT%3B%200%5D). To accommodate this, I switched the representation to a `Vec` with appropriate length checks. Since this required some inline changes, I also took the time to fix non-idomatic code that generates those values (switching from loops over mutable `Vec`s to iterators). These tasks were originally assigned to #51; I've checked off the boxes in there that I did here. The functional code stays the same -- it's just the loop structure …
=> Update soundness parameter to 80

src/auxinfo/auxinfo_commit.rs, src/auxinfo/participant.rs, src/keygen/keygen_commit.rs, src/keygen/participant.rs, src/paillier.rs, src/presign/participant.rs, src/protocol.rs, src/utils.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pifac.rs, src/zkp/pilog.rs, src/zkp/pimod.rs, src/zkp/piprm.rs, src/zkp/pisch.rs
This PR addresses #29 by modifying existing library functions so that every function which involves sampling values nondeterministically is parameterized with an rng to do this sampling. This also addresses #28 as the library itself should not call any of its own rngs, thus making tests deterministic once an rng is initialized.
More specifically, this PR adds a test-only function called `get_test_rng()` to utils.rs which samples a random seed, prints the seed to stderr, and returns an rng seeded with this seed. This function is called only once per test and is only called in functions with the `#[test]` decorator. 
To check that I covered all of the cases, I made sure OsRng and StdRng are not used anywhere in the library except for the  `get_test_rng()` function, and I also made sure …
=> Parameterize all random functions with an RNG

src/paillier.rs, src/presign/participant.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pilog.rs
This PR swaps out the use of `BigNumber` in `PaillierEncryptionKey::encrypt` and `PaillierDecryptionKey::decrypt` with `PaillierCiphertext`. Right now `PaillierCiphertext` is a thin wrapper around `BigNumber`, but future work will aim to hide that behind a cleaner interface.
This is work towards addressing Issue #59.
=> Use `PaillierCiphertext` in `encrypt` and `decrypt`

src/zkp/setup.rs
Closes #42
This issue was listed as a bug because I thought that the `PiMod` proof may have been removed entirely at some point (because it was commented out). Luckily, it was not removed, just moved to the correct point in the protocol (round 3, where it's supposed to live, vs round 1, where the `ZkSetupParameters` are made). I read through the protocol description and the code and everything seems to be in the correct place.
=> remove commented-out dead PiMod code

src/paillier.rs, src/presign/participant.rs, src/presign/round_three.rs, src/presign/round_two.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pilog.rs
This commit replaces the use of `BigNumber` with `PaillierCiphertext` where needed in the ZKPs. It also adds a `to_bytes` method to `PaillierCiphertext` to avoid needing to explicitly call the `BigNumber::to_bytes` method. Further hiding of the underlying `BigNumber` value will be made once Issue #64 is addressed.
Closes #63.
=> Use `PaillierCiphertext` in ZKPs

src/paillier.rs, src/presign/participant.rs, src/presign/round_one.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pilog.rs
This PR adds a `PaillierNonce` type which wraps a `BigNumber`, and utilizes this new type where needed in the various ZKPs. The PR also removes an unnecessary check that the generated nonce is non-zero (the check is unnecessary as we already to such a check during nonce generation).
Like with the previous PRs around adding these wrapper types, we do need to add a bunch of `.0`s to make things work. Going forward these will be removed when we start hiding the visibility of the underlying `BigNumber` type.
Closes #62. Once #40 is complete we can swap out the underlying `BigNumber` with `ZStarN`.
=> Add `PaillierNonce` wrapper to API

src/presign/participant.rs, src/presign/round_one.rs, src/presign/round_three.rs, src/presign/round_two.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pilog.rs
This MR replaces the use of the explicit modulus with the Paillier encryption key in `pilog`, `pienc`, and `piaffg`, and does associated cleanup in those files.
Note that, occasionally, we still need to extract the modulus and work with it. This should be unnecessary once #64 and #118 are addressed.
Closes #120.
=> Replace `N0: BigNumber` with `pk: PaillierEncryptionKey` in ZKPs.

src/errors.rs, src/presign/participant.rs, src/protocol.rs
This PR addresses #57 by removing the remaining asserts from the main library (there weren't many left). There was an assert check that message.to() == self.id in one of the subprotocols, so I moved it to the top level process_single_message() function.
=> Remove remaining asserts from library code

src/presign/participant.rs, src/utils.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pifac.rs, src/zkp/pilog.rs
Closes #85 
This fixes a couple of little bugs around sampling. In one or two places, the ranges we sampled from weren't quite correct. A range used for testing only was not correct. And the general plus/minus range sampling was off by one.
I also made a couple of quality-of-life improvements, including adjusting the names of the sampling functions (open to alternate suggestions if you don't like these changes) and adding another convenience function for a common sampling format.
This review is kind of detail-oriented because there are so many little ranges. I would prefer a focus on making sure that the changes don't change anything in the code (beyond the bugs noted inline). Don't worry about comparing to the paper -- I did this as I went, but I think we can re-audit that as we do the …
=> Fix tiny bounds-sampling bugs and adjust sampling calls

src/paillier.rs, src/presign/participant.rs
Closes #100. Closes #101.
This adds some fairly standard tests for Paillier encryption + decryption.
It also addresses something I'm not sure is a practical issue: the paper says
> We represent integers modulo N in the interval {−N/2, . . . , N/2} (rather than the canonical representation); this convention is crucial to the security analysis.
I'm not sure if this is also crucial to the _practical_ security of the library, but we encrypt a lot of things drawn from a range like `+/- 2^ell`. I wanted some kind of bounds check on encrypted messages, so I check that they're in the `[-N/2, N/2]` range. Then, to make decryption correct in the most reasonable way, I convert the output from the default canonical representation `[0, N)` to the range used in the protocol.
=> Add tests for Paillier encryption and decryption

src/paillier.rs, src/presign/participant.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pilog.rs
The PR adds an `PaillierEncryptionKey::multiply_and_add` method that allows us to hide the internals of `PaillierEncryptionKey`. Once we've addressed #107 we should be able to remove `PaillierEncryptionKey::n` and thus hide all the internals of the module.
Closes #64.
=> Add `PaillierEncryptionKey::multiply_and_add`

src/paillier.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pilog.rs
This PR adds an `encrypt_with_nonce` method to `PaillierEncryptionKey`, allowing one to either generate a new (ciphertext, nonce) tuple using `encrypt`, or generate a ciphertext that results from a given (plaintext, nonce) tuple using `encrypt_with_nonce`.
Currently, `encrypt_with_nonce` is only used internally. The plan is to use it in the ZKPs that currently do the encryption "by hand" (e.g., [here](https://github.com/boltlabs-inc/tss-ecdsa/blob/main/src/zkp/pilog.rs#L117)). However, that will require a bigger change to pass the `PaillierEncryptionKey` to the ZKPs rather than the particular modulus `N` (e.g., we'll need to replace `N0: BigNumber` [here](https://github.com/boltlabs-inc/tss-ecdsa/blob/main/src/zkp/pilog.rs#L44) with `pk: PallierEncryptionKey`), so I'll leave that change …
=> Add `encrypt_with_nonce` method to `PaillierEncryptionKey`

src/auxinfo/info.rs, src/auxinfo/participant.rs, src/errors.rs, src/paillier.rs, src/presign/round_one.rs, src/presign/round_two.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pilog.rs, src/zkp/setup.rs
This renames all the Paillier types to not have the word `Paillier` in them. I decided not to put the path inline where we use it (e.g. `pailler::Type`) because we don't have any other ciphertext or nonce or encryption key types that it might get confused with.
Closes #119.
=> Rename pailler types without paillier

.github/workflows/ignored_tests.yml, .github/workflows/main.yml, .gitignore, Cargo.toml, Makefile.toml, README.md
This PR makes the following changes:
- Pins Rust compiler version to avoid Clippy failures on new Rust version releases.
- Switches libpaillier backend to use openssl.
- Compiles project in release version for faster test execution time. Use new `cargo make` or `cargo make check` for checking code without release mode.
- Uses rust-cache GitHub Action for caching Rust dependencies during compilation.
This should cut down on build time from ~30 minutes to ~10 minutes when building from scratch. Smaller changes should be even quicker if no recompilation is necessary. Here are runtime compiling from scratch and running `cargo make ci` locally (by no means rigorous, repeatable results!):
```
Original Times `cargo make ci` execution time using Rust backend for unknown_order crate:
- cargo clean …
```
=> CI Updates for Faster Execution.

src/auxinfo/info.rs, src/parameters.rs, src/presign/participant.rs, src/presign/round_one.rs, src/zkp/pienc.rs
Closes #46 
- adds high-level and inline docs
- renames every variable :sweat_smile: 
- pull out transcript-writing to function
Rust question: I updated the `new` functions in here to take stuff by value since that is our best practice (e.g. let the callers decide whether to clone). However, I also found this incredibly inefficient so made #135 to try and limit that ownership-taking. Since the long game is to make all the `new` methods take things by value anyway, should I put all those clones back where they started?
I'm open to aesthetic feedback on this. I tried to strike an appropriate balance with names, per-field docs, and comments referencing back to the notation in the paper. But in the end this is for other people as well as myself so I'd like to know if you would like more or …
=> Add documentation and code tweaks to PiEnc

src/errors.rs, src/lib.rs, src/zkstar.rs
This PR addresses issue #40 and adds: 
1.`ZKStarN`: struct that represents elements of the group. An instance of `ZKStarN` has a `value` that represents the group element and a modulus of the group (i.e. `builder`) passed by reference as an instance of `ZStarNBuilder`. An instance of `ZKStarN` can only be constructed after validating that  a `ZStarNUnverified` is a proper member of the group (i.e. not zero, relatively prime to the modulus, smaller than the modulus) vis a vis the modulus defined by `ZStarNBuilder` .  An instance of `ZKStarN` can be serialized, in which case only its value is serialized. 
2.`ZStarNUnverified`: struct which represents elements that have not yet been validated as proper members of the group. In order to construct an element of `ZKStarN` from its serialized …
=> Add ZKStarN, ZStarNUnverified and ZStarNBuilder structs

benches/e2e_benchmark.rs, examples/network/server.rs, src/auxinfo/auxinfo_commit.rs, src/auxinfo/participant.rs, src/auxinfo/proof.rs, src/broadcast/data.rs, src/broadcast/participant.rs, src/errors.rs, src/keygen/keygen_commit.rs, src/keygen/participant.rs, src/paillier.rs, src/presign/participant.rs, src/presign/round_one.rs, src/presign/round_three.rs, src/presign/round_two.rs, src/protocol.rs, src/storage.rs, src/utils.rs, src/zkp/pisch.rs
This PR removes all of the instances of bail! and bail_context! from the codebase. I introduced some new errors for cases which where previously handled by bails, but I'm starting to think that there are too many error variants to be useful. I like how FailedToVerifyProof consolidates different ways of a proof failing, and we could probably do something similar for some of these other variants.
I also think there's like three kinds of errors which would require different control flows to handle: 
"Expected": Things like looking for a contents from a message that hasn't been received yet. Eventually this will probably resolve and so not much more needs to be done besides trying again later
"Malicious": Things like a proof failing that should only happen if a Participant doesn't follow the …
=> Remove bail! errors from codebase

src/ring_pedersen.rs, src/zkp/piprm.rs
This PR adds a bunch of documentation and variable renaming to improve the overall code quality of `piprm.rs`. In addition, it removes `PiPrmInput` in place of using `RingPedersen` directly.
Closes #51.
=> Improve code quality of `PiPrmProof`

src/ring_pedersen.rs, src/zkp/piprm.rs
Closes #111.
Adds a bunch of tests for `PiPrmProof`:
* Choose bad secret input lambda
* Send a proof with too few and too many elements
* Swap one or more of the challenges (e_i) for incorrect values (e.g. not derived from the transcript).
* Swap one or more commitments (A_i) for incorrect values
* Swap one or more responses (z_i) for incorrect values
* Verify the proof with different common input (N, s, t) than was used to create it
=> More comprehensive tests for `PiPrmProof`

src/auxinfo/proof.rs, src/presign/participant.rs, src/presign/round_one.rs, src/presign/round_three.rs, src/presign/round_two.rs, src/ring_pedersen.rs, src/zkp/mod.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pifac.rs, src/zkp/pilog.rs, src/zkp/pimod.rs, src/zkp/piprm.rs, src/zkp/pisch.rs
Closes #49.
This PR adds a `Transcript` argument to both the `Proof::prove` and `Proof::verify` functions to avoid having both `prove` and `prove_with_transcript` methods for some of the implemented zero knowledge proofs.
This commit also makes a couple of other minor changes:
* It adds documentation to the `Proof` trait.
* It moves the `rng` argument in `Proof::prove` to the end to be more consistent with some other uses of `rng` in the library.
=> Add `Transcript` to `Proof` trait

CONTRIBUTING.md, Cargo.toml, examples/network/main.rs, src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/messages.rs, src/paillier.rs, src/presign/participant.rs, src/protocol.rs, src/utils.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pilog.rs, src/zkp/pimod.rs, src/zkp/piprm.rs, src/zkp/pisch.rs
Closes #31
- Add logging events and spans to main functions.
- Set logging for unit tests and example application.
- Add documentation on how logging works and how to add new logging events and spans.
=> Add logging support for our library.

src/errors.rs, src/presign/record.rs, src/protocol.rs, src/utils.rs, src/zkp/pimod.rs, src/zkstar.rs
This PR attempts to consolidate some error types, particularly around proof generation, addressing issue #158 .
For this PR I kept the `verify_err!` macro in place so that a later PR can switch it to a logging one.
For parts of the code made less descriptive by switching the error type, I left a comment indicating the reason for the failure. Once logging is done, this is the text which should be logged
Potential Issue: This makes some tests less specific, as they are currently set up to look for specific errors to be thrown. How much do we care about this? (Personally, I think this is fine). If we care, is there an easy way to achieve this same effect through the automated checking of log files? 
Suggestion: The PR text mentions consolidating these into an error like …
=> Consolidate Errors

src/auxinfo/participant.rs, src/keygen/participant.rs, src/storage.rs
Closes #176.
The `transfer` method is used when we need to move an entry from local storage to main storage. It simplifies a bunch of the manual retrieve/store code in some of the participants.
=> Adds `transfer` method to `Storage`

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs, src/storage.rs, src/utils.rs
Closes #177.
This (Draft!) MR replaces the `Storage::store` and `Storage::retrieve` methods with version that auto serialize/deserialize.
Currently, this MR adds `Storage::store_serialized` and `Storage::retrieve_deserialized`. Once #178 is merged in we'll be able to consolidate these two version of both `store` and `retrieve`.
=> Replace `Storage::store` and `Storage::retrieve` with auto-(de)serialized versions

src/auxinfo/participant.rs, src/keygen/participant.rs, src/presign/participant.rs, src/storage.rs, src/utils.rs
Closes #186.
This PR replaces the use of `StorableType` in the `Storage` API with using `T: Storable` to aid in eventually replacing `StorableType` with local versions.
=> Move to using `T: Storable` instead of `StorableType` in `Storage` API

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/message_queue.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs, src/storage.rs
Closes #179 
This updates the `ProtocolParticipant` trait to define an output type and to add the `process_message` driver function to the trait.
Half the protocols (broadcast, presign) were already consistent with the new return type, so those didn't really change. The other half (keygen, auxinfo), will require a lot of changes to thread checking-whether-outputs-are-ready throughout the implementation. To preserve reviewer sanity, I've pushed that work to #193 and #194. I've tried to document inline some of the most obvious places where this will change.
I would particularly like reviewers to read the documentation of the `process_message` function and give feedback on whether the output type makes sense! I experimented with much wordier, more custom types to try to describe what was …
=> Define return types for subprotocols

src/broadcast/participant.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs, src/storage.rs
Closes #190.
This commit also renames `StorableType` to `MainStorageType` to make it's purpose more clear.
=> Move presign storage types to `presign::StorageType`

Cargo.toml, src/auxinfo/auxinfo_commit.rs, src/auxinfo/info.rs, src/auxinfo/participant.rs, src/broadcast/participant.rs, src/errors.rs, src/keygen/participant.rs, src/paillier.rs, src/participant.rs, src/presign/participant.rs, src/presign/record.rs, src/presign/round_one.rs, src/presign/round_three.rs, src/presign/round_two.rs, src/ring_pedersen.rs, src/utils.rs
Closes #193 
I let this PR expand out of reasonable scope; I apologize to the reviewers.
Primary changes are:
- Updates the auxinfo protocol to return public and private key material
- Adds a participant ID field to public key material to indicate who it belongs to
- Adds conditions to aux info tests to make sure the outputs are as expected
- Improves code quality of `AuxInfo{Commit, Decommit, Public, Private, Witness}`, including limiting visibility of parameters to add confidence that they're well-formed, adding validation at construction and deserialization, zeroizing secrets, and adding custom debug implementations to some maybe-secret types.
- Moves some existing functionality (`process_ready_message`) into `ProtocolParticipant` 
- Adds a new method to combine `ProcessOutcome`s in a …
=> Thread output-return throughout auxinfo

src/broadcast/participant.rs, src/local_storage.rs
Closes #211.
The last `Participant` that needs to use `LocalStorage`. This change also requires adding `LocalStorage::retrieve_mut` to retrieve a mutable reference to data in `LocalStorage`.
=> Change `BroadcastParticipant` to use our type-based local storage

src/auxinfo/participant.rs, src/keygen/keyshare.rs, src/keygen/participant.rs
Closes #194 
This updates all the key generation message handlers to return `ProcessOutcome`s instead of lists of messages, and updates the tests to validate the returned outcomes.
I also made #207 with suggested code quality improvements :angel:
=> Fix keygen output

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/local_storage.rs, src/participant.rs, src/presign/participant.rs, src/storage.rs
Closes #222.
This change replaces `ProtocolParticipant::storage` with `ProtocolParticipant::local_storage` so we can move towards removing the need for `main_storage` in the underlying protocols. This PR also simplifies the code in `process_ready_message`, as now we can directly access `LocalStorage` through the new `local_storage` API.
=> Replace storage trait methods

src/auxinfo/participant.rs, src/keygen/participant.rs, src/presign/participant.rs, src/protocol.rs, src/storage.rs, src/utils.rs
Closes #226.
This commit removes the use of `main_storage` almost entirely from `auxinfo` and `keygen`, only using it currently to store values to signal protocol completion for other protocols.
This commit also moves some functionality from `utils.rs` to `Storage`. This'll make it easier to isolate components directly related to persistent storage to be removed in future commits.
=> Remove most uses  of `main_storage` from `auxinfo` and `keygen`

Cargo.toml, src/auxinfo/auxinfo_commit.rs, src/auxinfo/info.rs, src/auxinfo/participant.rs, src/errors.rs, src/keygen/keygen_commit.rs, src/keygen/participant.rs, src/paillier.rs, src/protocol.rs, src/ring_pedersen.rs, src/utils.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pifac.rs, src/zkp/pilog.rs, src/zkp/pimod.rs, src/zkp/piprm.rs, src/zkp/pisch.rs, src/zkstar.rs
This PR removes the `verify_err!` macro and removes the string portion of `InternalError::FailedToVerifyProof`. The context for why the proof failed is now logged with `tracing::warn`
=> Log Proof Verification Errors

src/auxinfo/auxinfo_commit.rs, src/auxinfo/proof.rs, src/keygen/keygen_commit.rs, src/keygen/participant.rs, src/local_storage.rs, src/message_queue.rs, src/messages.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs, src/storage.rs
Addresses #162 : 
This change adds documentation for the `Identifier` struct and specifies its different uses and properties. 
It also clarifies that `identifier`s refers to session/sub-session identifiers rather than unique id for specific message values.
=> Add more documentation to clarify the role of identifiers.

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/keyshare.rs, src/keygen/participant.rs, src/local_storage.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs
Closes #229.
We still need main storage in `presign`, but now we store into main storage in `Participant::process_single_message` rather than in each individual sub-protocol.
This PR also removes some unnecessarily serialization in `ProgressStore`. Apologies for the bonus code cleanup in this PR, but it's pretty small :-).
=> Remove main storage from `auxinfo` and `keygen`

benches/e2e_benchmark.rs, examples/network/server.rs, src/auxinfo/info.rs, src/keygen/keyshare.rs, src/lib.rs, src/presign/record.rs, src/protocol.rs
Closes #203
This updates the output type of external-facing message processing and updates the tests to check that it shows up when we expect it to.
I'm marking as a draft for now because it overlaps a fair amount with #230 and #231 in the `process_single_message` method and I don't want to destroy that merge. However, it's ready for review.
This highlights the need to fix the debug view for `KeySharePrivate` -- maybe this could be done in #207.
=> Return output from `process_single_message`

src/presign/participant.rs, src/protocol.rs, src/storage.rs
Closes #236.
This commit adds an `Input` type to `PresignParticipant` that is more meaningful than just using `Storage`. In particular, it contains the necessary auxinfo and keygen information for `PresignParticipant` to operate. This `Input` can be constructed in `process_single_message` once `auxinfo` and `keygen` are completed.
=> Add meaningful `Input` type to `PresignParticipant`

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/local_storage.rs, src/participant.rs, src/presign/participant.rs
Closes #217.
Since each `Participant` now exists within a single session, we no longer need to store `Identifier` in `LocalStorage`. This commit removes that, although leaves `MessageQueue` untouched (to be addressed in #261).
=> Remove `Identifier` from `LocalStorage`

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/errors.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs
Closes #160.
This allows a caller to tell when a protocol has successfully completed. In addition, this commit adds a `status` enum to each `ProtocolParticipant` instantiation to track protocol status. (Currently just `Initialized` and `TerminatedSuccessfully` is used.)
=> Add `is_done` method to `ProtocolParticipant` trait

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/local_storage.rs, src/message_queue.rs, src/messages.rs, src/participant.rs, src/presign/participant.rs
Closes #261.
Now that session IDs are no longer used in `Participant`s, we can remove them from the `MessageQueue` and `ProgressStore` structs used in `LocalStorage`.
=> Remove `Identifier` from `MessageQueue` and `ProgressStore`

benches/e2e_benchmark.rs, src/presign/participant.rs
Closes #281
This isn't the best solution because it benchmarks some setup time. I couldn't figure out a good way to call the `init_new_player_set` function outside the benchmark iteration function, but I am open to suggestions!
=> Fix benchmark bug

README.md, rust-toolchain.toml
Closes #300 
I added a rust toolchain file, but since this update doesn't actually introduce any changes we need to fix, I left the MSRV in the README as the previous version. Is that reasonable?
I also looked into renovate (link in issue) and it seems a lot more powerful than we need. I'm just going to add "make a new issue for the next version" as a task in each update issue and hopefully we can be self-perpetuating.
=> update rust version

src/auxinfo/participant.rs, src/auxinfo/proof.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/presign/participant.rs, src/protocol.rs, src/zkp/mod.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pifac.rs, src/zkp/pilog.rs, src/zkp/pimod.rs, src/zkp/piprm.rs, src/zkp/pisch.rs
Closes #240: Add the participant ids and ECDSA group order and base point to the context in keygen, auxinfo and presign.
=> Add ECDSA parameters to context including group order and base point.

src/auxinfo/auxinfo_commit.rs, src/auxinfo/participant.rs, src/auxinfo/proof.rs, src/broadcast/data.rs, src/broadcast/participant.rs, src/errors.rs, src/keygen/keygen_commit.rs, src/keygen/participant.rs, src/messages.rs, src/paillier.rs, src/presign/participant.rs, src/presign/record.rs, src/presign/round_one.rs, src/presign/round_three.rs, src/presign/round_two.rs, src/protocol.rs, src/ring_pedersen.rs, src/utils.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pifac.rs, src/zkp/pilog.rs, src/zkp/pimod.rs, src/zkp/piprm.rs, src/zkp/pisch.rs, src/zkstar.rs
Addresses a component of #157 by further reducing the number of error types. The lost context is instead replaced by logging
Also closes #266
=> Consolidate Error Messages

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs
Close #326 : Add the session identifier and input to `ProtocolParticipant` instantiations in `Keygen`, `Broadcast`, `Presign`, `Auxinfo`. These fields will later be incorporated into the different contexts.
=> Add sid and input to ProtocolParticipant

src/auxinfo/participant.rs, src/protocol.rs
Closes #141 : Add session identifier to `SharedContext`.
=> Add session identifier to shared context.

src/presign/participant.rs
Closes #325.
This commit fixes a security bug in the presign protocol. In the protocol specification, each round requires that all messages from the prior round be received (and verified) before proceeding. Unfortunately, this is not what the code was doing, particular in round two of the protocol, where it would process a participant's message as soon as it was received.
This commit fixes that bug, alongside further aligning the presign implementation with keygen and auxinfo in terms of code structure.
This commit does NOT address any other issues related to a security audit.
=> Fix security bug in presign protocol

src/auxinfo/info.rs, src/presign/participant.rs, src/protocol.rs
Close #241 : Add AuxinfoPublic parameters to Presign specific context a long with shared global parameters defined by `SharedContext`.
=> Create PresignContext with AuxInfoPublic parameters.

src/auxinfo/auxinfo_commit.rs, src/auxinfo/info.rs, src/auxinfo/participant.rs, src/broadcast/participant.rs, src/errors.rs, src/keygen/keyshare.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs
Closes #248.
This PR does the following:
- Updates constructors for `Participant` and `ProtocolParticipant`s to return `Result`s.
- Adds validation to the presign input type (and adds tests of this behavior)
This issue was not super well scoped, so I moved some of the changes around:
- Auxinfo still doesn't have input, so it's blocked on #242. I added "validate the input" as a step in that issue, but it might be better as its own issue / PR.
- The issue described some kind of `validate_input` function, but I found that moving validation to a function other than the constructor was not as good, because I'd have to either make some intermediary type or pass a bunch of parameters and it seemed to weaken the guarantees I want ("types that hold inputs have always have validated those inputs"). …
=> Validate presign inputs

src/presign/participant.rs, src/presign/round_one.rs, src/presign/round_three.rs, src/presign/round_two.rs
Closes #214.
This PR splits the `from_message` method in `presign::round_...` into a separate `TryFrom<&Message>` implementation and a `verify` method.
=> Refactor presign message verification

.github/workflows/main.yml, benches/e2e_benchmark.rs, examples/threaded_example/main.rs, src/keygen/keyshare.rs, src/keygen/mod.rs, src/keygen/participant.rs, src/lib.rs, src/presign/participant.rs, src/presign/record.rs, src/presign/round_three.rs, src/presign/round_two.rs, src/protocol.rs, src/utils.rs
Closes #243.
Closes #252.
This adds the `global_rid` value to the output of keygen. The value is a random string, and it's only used as context for strong fiat-Shamir in proofs. This PR does not include adding it to the proofs. I forgot that #252 was a separate issue so I accidentally did it here. Big changes include:
- Replacing all uses of the tuple returned from keygen with the new `Output` type instead
- Adjusting visibility of `CurvePoint`, which changed includes all over the place and is a side benefit of pulling public-key-related functions into the keygen output type.
Reviewing: I'm pretty confident that I pulled the global `rid` value correctly, so I'm looking more for comments on the ergonomics of the `Output` type.
=> Add randomness to keygen output

src/lib.rs, src/messages.rs
The `messages` module needs to be made `pub` so users of this API can utilize their types. This is needed for the networking POC.
=> Expose additional types for networking POC to work.

benches/e2e_benchmark.rs, examples/threaded_example/threaded.rs, src/auxinfo/participant.rs, src/errors.rs, src/keygen/participant.rs, src/lib.rs, src/presign/participant.rs, src/protocol.rs, src/utils.rs
Closes #339 
This adds guarantees about `ParticipantConfig` behavior (must be correct size, contain unique identifiers) by putting it in its own module and locking down the constructor. This doesn't address the problem of configs being invalid after deserialization, but that's a known problem (#6) for a lot of types.
Also adds a method to create an `Identifier` _not_ uniformly at random, like we expect to happen in deployments that don't involve a trusted third party.
Future work:
- Figure out deserialization validation and do it everywhere.
- There's duplication between these methods and the `ProtocolParticipant` methods on ids. Right now we copy the two config fields into `ProtocolParticipant` but it would be cleaner to just use the existing type.
=> clean up participant config API

src/presign/participant.rs, src/presign/round_one.rs, src/presign/round_two.rs, src/zkp/mod.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs
Closes #396 and #398 
Units tests are refactored to work with new lifetime requirements and cleaned up.
=>  Relax Proof Input Ownership Requirements

src/auxinfo/participant.rs, src/keygen/participant.rs, src/local_storage.rs
Adds a new `remove()` function to the Storage API, which removes an item from storage and returns it to the call. Replaces a few end-of-protocol calls to `retrieve` with `remove`, but only where there is no chance that the item will be needed again. Replacing other instances of `retrieve` with `remove` will require more care, especially when considering the possibility of `ProtocolError`s
Closes #288
=> 288-remove

benches/e2e_benchmark.rs, examples/threaded_example/threaded.rs, examples/threaded_example/utils.rs, src/auxinfo/info.rs, src/auxinfo/mod.rs, src/auxinfo/output.rs, src/auxinfo/participant.rs, src/auxinfo/proof.rs, src/lib.rs, src/presign/participant.rs, src/presign/round_three.rs, src/presign/round_two.rs, src/protocol.rs
Closes #406.
This adds an `Output` type to auxinfo and also rejigs the public-facing module structure a bit (hence all the changes in the includes).
Looking for:
- general Rust review -- is this a good API?
- test ideas -- is there anything I missed about the structure of the auxinfo output that should be checked here?
=> Add an output type for auxinfo

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs
This handles part of #290 but does not complete it. 
The code landed in a weird intermediate state where the `ProtocolParticipant` types all held their inputs as a field, but the input was also passed around to all the methods. This PR removes that duplication (and in the process, removes the need to clone inputs for every new message received, reducing memory usage and the number of copies of secrets floating around).
=> reduces passing of inputs in protocols

src/errors.rs, src/keygen/keyshare.rs, src/utils.rs
Addresses part of #429 but doesn't complete it.
This has some overlapping changes with #433, specifically the `ParseBytes` utility. It is smaller and plausibly easier to review than #433, so maybe do this one first.
=> add storage methods for keygen

src/auxinfo/info.rs, src/errors.rs, src/paillier.rs
This addresses part of #429 but does not complete it.
I decided to break 429 into pieces because this is already fairly large.
It adds equality checking and manual serialization / deserialization method to `AuxInfoPrivate` and its underlying `DecryptionKey`.
This change flags again the unsuitability of the `libpaillier` dependency we're using; it doesn't do any validation of the correctness of a deserialized decryption key. I added a check but I only came up with one property that we can check without having the factors handy. Maybe there are other things related lengths of the fields?
=> add storage methods for auxinfo

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/message_queue.rs, src/participant.rs, src/presign/participant.rs
This PR addresses issue #304, in which a possible unfavorable message ordering causes errors. Specifically, it was possible for a protocol to terminate locally before receiving a Ready message from yourself, causing the receipt of such message to trigger an error. To address this, the purpose of Ready messages was changed: instead of needing to receive a Ready from all players prior to starting a protocol instance (which is not required in the paper), we instead become "Ready" after receiving a Ready message from ourselves (so in practice, whoever is controlling the Participant can make them ready to run a protocol by sending a message). 
This by itself doesn't fully fix the issue, so the other change is to not process any messages before receiving this initial Ready. Code was added to …
=> Debug ProtocolAlreadyTerminated tests failure

src/auxinfo/info.rs, src/keygen/keyshare.rs, src/presign/record.rs, src/utils.rs
Closes #429
Adds serialization methods and equality checking for presign records. Also adds a utility method in the parse-bytes function to read an 8-byte length, since we use that everywhere.
=> Add storage utility methods for presign

src/zkp/pifac.rs
(CI runs ignored tests on main branch).
=> Change broken test from ignored to truly disabled.

benches/e2e_benchmark.rs, examples/threaded_example/threaded.rs, src/lib.rs, src/presign/input.rs, src/presign/mod.rs, src/presign/participant.rs, src/presign/round_three.rs, src/protocol.rs
Closes #451
This standardizes the imports for presign to align with those of the other two modules. It reduces publicity of a variety of modules, reduces renaming of the form `module_name::Thing as ModuleNameThing`, and pulls presign input into its own self-contained module.
The diff is big, but most of it is the input module. That code didn't change except for method publicity and two accessor methods, which I'll note inline.
I picked this up as a precursor to #424, which I think will benefit from the cleaned-up module structure.
=> Rearrange presign module

src/auxinfo/participant.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs, src/presign/record.rs, src/sign/participant.rs
Closes #423 
This handles the checklist in the issue, basically just adding infrastructure that will need to be in place to implement the actual protocol. There are a few utility methods for interacting with the `PresignRecord` input. Some things will likely change in future iterations, like exactly which types we keep in storage.
I also removed the `Ready` types from all participant storage modules; these were made obsolete with the refactor in #440 but didn't get removed at that time.
=> implement InnerProtocolParticipant for signing

src/auxinfo/auxinfo_commit.rs, src/auxinfo/info.rs, src/auxinfo/participant.rs, src/ring_pedersen.rs, src/zkp/piprm.rs
@marsella I'm less confident about how this PR turned out. Lmk what you think. (See my comments below)
=> Relax Ownership Requirements for piprm.

src/zkp/pimod.rs
Closes #419
There are more issues to fix here, I think, in terms of code quality, but this should fix the specific "spam the error logs" problem we've seen. Before I close this I will write another issue with some more specifics.
=> remove non-failure error from pimod

benches/e2e_benchmark.rs, src/auxinfo/output.rs, src/auxinfo/participant.rs, src/keygen/keyshare.rs, src/keygen/participant.rs, src/presign/participant.rs, src/presign/record.rs, src/protocol.rs, src/utils.rs, src/zkp/piaffg.rs, src/zkp/pilog.rs, src/zkp/pisch.rs
Closes #424
This adds a basic happy test for presigning, defines the characteristics that a valid set of `PresignRecord`s should satisfy, and adds a method to simulate a valid `presign` run.
There's lots of boilerplate to get the presign test running; this is mostly copied from the equivalent keygen and auxinfo tests. I think some of this could be extracted into a testing utility module because many of the functionalities (e.g. maintain an inbox to store and "send" messages) are the same across different participant types. I also think some of them could be simplified (e.g. we don't need separate inboxes for each party; we can just make one big inbox for all messages). But I refrain from addressing that here.
There's a bit of rearranging of code, like for the `simulate` methods on keygen …
=> 424 presign testing

src/zkp/pifac.rs
=> 113 pifac tests

src/protocol.rs, src/sign/non_interactive_sign/participant.rs
Closes #470
Fixes a bug where we didn't validate the input to signing correctly, and fixes the test where we made exactly that mistake.
=> fix validation bug in new signer

Cargo.toml, src/presign/record.rs, src/protocol.rs, src/sign/non_interactive_sign/participant.rs
Closes #444
Some of our core cryptography libraries were way out of date. Now they aren't. Most changes are just to method names and module organization.
=> update k256, sha2 versions

src/auxinfo/output.rs, src/keygen/mod.rs, src/keygen/output.rs, src/keygen/participant.rs, src/presign/input.rs
Closes #376 
This adds `into_parts` and `from_parts` methods for keygen output so that we can reconstruct them in products that need to store the output. It also:
- Moves the keygen output to its own module
- Updates the simulate methods for keygen and auxinfo to only produce valid outputs
- Updates the presign input validation to reduce double-checking of things that are already checked in the individual output constructors.
=> add keygen output constructor and tests

.github/workflows/ignored_tests.yml
It looks like our run-on-merge-to-main tests started failing because a dependency needs a higher minimum rust version. When we updated the other tests to pull the rust version from the `.toml` file, we didn't update these ones. Fixing now.
Please don't review until the tests run correctly, and note that we need to remove the line that runs these tests on PR before merging.
=> Fix ignored tests to use latest rust version

src/lib.rs, src/protocol.rs, src/sign/interactive_sign/participant.rs
Closes #426
This adds interactive signing to the public API. The only thing that had to change to make this possible was to add a condition that allows you to run a participant with `ProtocolType = InteractiveSign`. 
The much larger change here is to add an interactive-sign end-to-end test. There's some duplicated code relative to the non-interactive-sign e2e test but I simplified some of the mechanics relative to the older test; I might try to consolidate that. There's a lot of duplication in general with running these protocols and it might be helpful to write a generic-over-protocol-type runner. But it also might be confusing.
Open to recommendations on simplifying the test, otherwise I can make an issue to clean up the end-to-end tests after also adding non-interactive sign to the …
=> add interactive signing public API

src/lib.rs, src/protocol.rs, src/sign/interactive_sign/participant.rs, src/sign/non_interactive_sign/participant.rs
Closes #494 
This adds non-interactive signing to the public API, and paves the way to removing the non-protocol-correct DIY-signing. As in #493, the code changes are minimal; the changes to the tests and docs are more significant.
=> Add noninteractive signing to public API

README.md, src/auxinfo/auxinfo_commit.rs, src/broadcast/participant.rs, src/errors.rs, src/keygen/keygen_commit.rs, src/participant.rs, src/presign/participant.rs, src/presign/record.rs, src/presign/round_three.rs, src/sign/non_interactive_sign/participant.rs, src/zkp/piaffg.rs, src/zkp/pienc.rs, src/zkp/pifac.rs, src/zkp/pilog.rs, src/zkp/pimod.rs, src/zkp/piprm.rs, src/zkp/pisch.rs, src/zkstar.rs
=> 410 Add identifiable abort ids to Protocol errors

benches/README.md, examples/threaded_example/threaded.rs, src/keygen/output.rs, src/lib.rs, src/presign/record.rs, src/protocol.rs
Closes #427
This removes the outdated signing API (which didn't run the protocol as specified in the paper) and updates the examples that used it.
=> remove old signing API and update examples 

README.md, src/errors.rs, src/sign/interactive_sign/participant.rs, src/sign/mod.rs, src/sign/non_interactive_sign/participant.rs
Implements method to compute recoverable signatures. Closes Issue #508.
Tested by adding recoverable signature function call to sign unit tests.
Adds documentation for the threaded example CLI.
=> Add support recoverable signatures.

Cargo.toml
See Issue #513 for more details.
=> Include dependency to `rug` to fix compilation error.

src/errors.rs, src/keygen/keygen_commit.rs, src/keygen/keyshare.rs, src/keygen/participant.rs, src/keyrefresh/keyrefresh_commit.rs, src/keyrefresh/participant.rs, src/local_storage.rs, src/participant.rs
This PR fixes the following issues in KeyGen:
- *MAJOR -* Messages for past rounds overwrite the state.
- [Issue #527](https://github.com/boltlabs-inc/tss-ecdsa/issues/527)
- *MAJOR -* Schnorr proofs are not verified against the commitment.
- [Issue #515](https://github.com/boltlabs-inc/tss-ecdsa/issues/515).
- *MEDIUM -* Proofs can be replayed without knowledge of exponent.
- [Issue #149](https://github.com/boltlabs-inc/tss-ecdsa/issues/149#issuecomment-2066617606).
- *UNKNOWN -* Function `KeygenDecommit::verify` sets the fields in a copy so it does not actually verify these fields.
- *INFO -* Inconsistent handling of edge cases of key shares (0 vs q).
=> keygen: security fixes

src/auxinfo/participant.rs, src/presign/participant.rs, src/sign/non_interactive_sign/participant.rs
The policy is to never accept duplicate or conflicting messages, and to never overwrite existing values in storage.
See also https://github.com/boltlabs-inc/tss-ecdsa/pull/530 for the same in keygen and keyrefresh.
=> Reject repeated messages in the auxinfo and signing protocols

src/auxinfo/participant.rs, src/auxinfo/proof.rs, src/presign/participant.rs, src/presign/round_one.rs, src/presign/round_three.rs, src/presign/round_two.rs
This PR adds the participant ID to the context of each proof. This is as specified in the paper, such that there is no risk of someone replaying someone else’s proofs.
This applies to AuxInfo and PreSign. See https://github.com/boltlabs-inc/tss-ecdsa/pull/530 for the same in KeyGen and KeyRefresh.
=> Distinct proof contexts per participant

src/zkp/pilog.rs
Fix for #539.
This test uses a pool of pre-generated primes (~1000). It can happens that the test gets the same key twice while trying to generate two different ones.
=> fix-different-dk: make sure to use a different key in negative test

Cargo.toml, src/protocol.rs, src/utils.rs
Smol PR for cleaning up a few things.
The `Display` change uses the last 4 bytes instead of the first 4 bytes for pretty display purposes. As it is more likely that the underlying u128 will have these least significant digits vs the most significant digits. Printed, it now looks like `ParticipantId(0x77d6b86ab8)`.
This fixes an issue in our MPC Demo where IDs look like: `ParticipantId(00000000)` since they are seeded from u32 values (which are always zero in those most significant digits :face_exhaling: )
- Use our zeroizing in all unit tests.
- Remove unneeded Rocket dev dependency.
=> Update `Display` instance for `ParticipantIdentifier`

Cargo.toml, src/keygen/keyshare.rs, src/keyshare_export.rs, src/keyshare_export/pke.rs, src/keyshare_export/sodium.rs, src/lib.rs
Issue #537.
This is a variant with an abstraction over encryption libraries.
=> key-export-abstract: Import/export with abstract encryption library

src/keygen/keygen_commit.rs, src/keygen/output.rs, src/keygen/participant.rs, src/keyrefresh/participant.rs, src/protocol.rs, src/tshare/commit.rs, src/tshare/output.rs, src/tshare/participant.rs, src/zkp/pisch.rs
This PR adds a chain code field to the Tshare subprotocol. This way we can use the library in 4 different manners:
* Basic keygen
* Threshold keygen
* Basic HD wallet
* Threshold HD wallet
A unit test is added for each case.
=> Add chain code to tshare and create subprotocol helpers

src/tshare/participant.rs, src/utils.rs
This led to confusing output when running unit tests!
=> Fix Accidental Logging in Unit Tests

README.md, examples/threaded_example/threaded.rs, examples/threaded_example/utils.rs, src/auxinfo/output.rs, src/keygen/output.rs, src/protocol.rs, src/tshare/mod.rs, src/tshare/participant.rs, src/tshare/share.rs
Content:
- Insert the `tshare` conversion protocol in the example scenario.
- Refactor the coordinator to support subsets of participant workers.
- For presign and sign protocols, use a subset: the first 2 participants as an example.
- Add conversion functions between `keygen` and `tshare` outputs.
Try it with:
`cargo run --example threaded_example -- --number-of-workers=3`
=> tshare-example: Use threshold signature in the example app
