src/utils.rs
Fixes #54.
I realized while adding that documentation that these two methods are used in slightly different ways in the protocol, so I updated the documentation and functionality to reflect the expected usage.
- When sampling from a field (`F_q`) or integers mod N (`Z_N`), the upper bound (q, N) is an incorrect output
- When sampling from a plus-minus (`+/- q`), the upper and lower bounds (q, -q) are valid outputs
Requesting a cryptography review only from @tyurek to confirm correct usage and terminology.
=> update doc and fix tiny bounds bug in transcript sampling #54

Makefile.toml
=> add private docs to CI

CONTRIBUTING.md
=> Update CONTRIBUTING.md to include best practices.

benches/e2e_benchmark.rs, examples/gen_primes.rs, examples/network/client.rs, examples/network/server.rs, src/utils.rs
Fixes clippy lint errors :paperclip:
=> Fixes Clippy Error from update to Rust 1.67

src/paillier.rs
=> explain encryption implementation

src/zkp/pimod.rs
Closes #72
- Adds soundness check to proof verification methods
- Adds a test to make sure it doesn't happen again.
- Adds a basic "happy" test that proving and then verifying works.
PiMod is one of the proofs that have separate `prove()` and `prove_with_transcript()` methods (ditto `verify()`), so all these changes are sort of duplicated to make sure both versions are correct.
Review requests: Nothing special, this seemed pretty straightforward to me. Suggestions for making the tests less ugly are welcome, but all the duplication is going to go away once we do #49 so it's not a huge issue.
=> Fix soundness bug in PiMod proof #72

src/presign/participant.rs
Closes #123 
I traced the usage of these two elements `beta` and `beta_hat` in presigning. I feel confident about the change to the range -- there was a complicated explanation of the intended range but it was all about specific numbers rather than our overall parameters and was talking about doing something tricky. I think that was outdated documentation, and I fixed the range to match the protocol description (and the eventual proof verification in both paper and implementation that those two elements are in the expected range).
I also noticed something weird happening with the sign of those values. The protocol calls for it to sometimes be negative, but the implementation makes them always positive. When I changed the implementation to match the paper, a proof failed. This is to be …
=> fix sampling range for presigning elements

src/paillier.rs, src/zkp/pienc.rs
Closes #109
It adds the tests described in the issue. I didn't think of any others to put in.
It also fixes a bug! The `plaintext_mask` should not be passed with the proof. If the verifier knows the mask for the plaintext, they can unmask it. Yay for testing.
=> Add tests for PiEnc proofs

src/keygen/participant.rs, src/storage.rs
=> Add local `StorageType` to keygen protocol

src/auxinfo/participant.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs, src/presign/round_one.rs, src/protocol.rs, src/storage.rs
=> Change `PresignParticipant` to use new `LocalStorage` API

src/presign/participant.rs
Closes #198 
This updates all the presign message handlers to return `ProcessOutput`s instead of pairs of optional output + messages. The other task in the issue was to validate the returned outputs in the tests; sadly, there are no tests of the presign module alone. In the interest of not exploding this PR, I chose not to add any at this time.
=> Update presign to use ProcessOutput

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs
Closes #199
This adds `ProcessOutput` to all the broadcast handler messages.
I played around with a couple options for how I want the subprotocols to interact with the final output from the broadcast subprotocols and picked the one in this PR as my favorite. I originally planned to match on the `ProcessOutcome`, but it's kind of unwieldy because I end up calling functions twice (e.g. any message-processing has to be handled by both the `Processed` and `TerminatedForThisParticipant` arms, and any output processing by both `Terminated` and `TerminatedFTP`). This can also inform #203, which will involve handling `ProcessOutcome`s. 
I also updated the `ProcessOutcome` combining methods to reduce manual creation of outcomes and creation of one-element `Vec`s. I'm not as confident this is …
=> Thread process output through broadcast

src/zkp/piprm.rs
See discussion in issue #224 for more information.
=> Remove the bad_secret_totient_fails test, it does not test an actual attack.

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs
Close #237 : This PR also adds a method for retrieving that context.
=> Add a Context associated type with ProtocolParticipant. 

src/lib.rs
Closes #220.
This adds a bit more precision to the top-level library documentation about what the library implements and handles. 
Related issues: The documentation about requirements for the calling library is a bit sparse right now, but it will get expanded in #213, #218, and #219.
=> add caveats, precision to library docs #220

benches/README.md
Included README file for benchmarks.
=> Bench readme

src/local_storage.rs, src/presign/participant.rs, src/presign/record.rs, src/utils.rs
Addresses Issue #156 by adding error logs for all remaining instances of InternalInvariantFailed
=> Add error logs for remaining instances of InternalInvariantFailed

src/keygen/mod.rs, src/keygen/participant.rs, src/messages.rs, src/participant.rs
Closes #273
This PR contains comments and minor changes based on my audit of the keygen protocol.
=> Keygen protocol audit

src/lib.rs, src/protocol.rs
Closes #218, with a little extra on participant identifiers.
Requesting @Ra1issa as a reviewer since you have thought the most about session IDs.
=> Expand docs on caller requirements around ids

src/auxinfo/auxinfo_commit.rs, src/auxinfo/participant.rs, src/broadcast/participant.rs, src/errors.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs
Moved all_participants method to ProtocolParticipant
Wrote 4 negative tests for process_single_message()
=> "Closes #256":  Bad message routing tests

src/lib.rs
Closes #294.
Requesting @indomitableSwan as a reviewer. @gatoWololo might also take a pass for whether this makes sense.
=> add docs about networking requirements

.gitignore, Cargo.toml, examples/threaded_example/main.rs, src/auxinfo/mod.rs, src/auxinfo/participant.rs, src/keygen/mod.rs, src/keygen/participant.rs, src/lib.rs, src/presign/mod.rs, src/presign/participant.rs, src/protocol.rs
Closes #221
Here is the threaded example.
Overall the public API is shaping out well. I like that we expliclity pass the necessary inputs to each subprotocol and get the values back out.
There is some rough edges that I will add as comments in this PR.
=> Threaded Example using New API

.github/workflows/ignored_tests.yml, .github/workflows/main.yml
=> update rust version in CI #300

src/auxinfo/auxinfo_commit.rs, src/auxinfo/info.rs, src/auxinfo/mod.rs, src/auxinfo/participant.rs, src/auxinfo/proof.rs
Closes #275.
This PR audits the auxinfo protocol, adding comments to clarify the protocol alongside making several small code improvements.
=> Audit of auxinfo protocol

src/auxinfo/auxinfo_commit.rs, src/auxinfo/proof.rs, src/broadcast/data.rs, src/keygen/keygen_commit.rs, src/messages.rs, src/presign/round_one.rs, src/presign/round_three.rs, src/presign/round_two.rs, src/zkp/pisch.rs
=> Consolidate message type errors

src/keygen/keyshare.rs, src/lib.rs, src/participant.rs, src/presign/mod.rs, src/presign/participant.rs, src/presign/round_one.rs, src/presign/round_three.rs, src/presign/round_two.rs
Closes #277.
This PR includes comments and documentation to clarify the implementation of the presign protocol.
=> Audit of presign protocol

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/errors.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs
=> extract_message function on Broadcast Output

src/presign/record.rs, src/protocol.rs
Closes #354.
This PR includes minor refactoring, alongside comments addressing potential concerns.
=> Audit of signing code

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs
=> Return type changed

src/keygen/keyshare.rs, src/keygen/participant.rs, src/presign/participant.rs, src/presign/round_two.rs, src/protocol.rs
=> Improve code quality Keygen

src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs
=> InnerProtocolParticipant message other participants

examples/threaded_example/threaded.rs, examples/threaded_example/utils.rs
=> Clean up documentation for example code.

src/paillier.rs, src/zkp/pilog.rs
=> PiLog Tests

src/keygen/participant.rs, src/zkp/pisch.rs
=> Switch over `Pisch` to use new Proof trait.

src/presign/participant.rs, src/presign/round_three.rs, src/presign/round_two.rs, src/zkp/pilog.rs
=> Switch over pilog to use better proof trait: `Proof2`

src/zkp/piaffg.rs
=> PiAffg Tests

src/keygen/keygen_commit.rs, src/zkp/pisch.rs
=> 389 standardize naming PiSch

src/zkp/pisch.rs
=> 391 docs PiSch

benches/e2e_benchmark.rs, examples/threaded_example/threaded.rs, src/auxinfo/participant.rs, src/broadcast/participant.rs, src/keygen/keygen_commit.rs, src/keygen/participant.rs, src/messages.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs
=> Pull serialization new message

src/auxinfo/proof.rs, src/zkp/pifac.rs
=> Relax ownership requirements in PiFac using new proof trait.

README.md, rust-toolchain.toml, src/keygen/keygen_commit.rs
Closes #430
Just one minor clippy change.
=> update rust version to 1.71

src/zkp/pisch.rs
=> 115 pisch tests

src/utils.rs, src/zkp/pisch.rs
=> 453 code quality nits PiSch

src/zkp/pimod.rs
=> 114 PiMod Tests

src/auxinfo/mod.rs, src/auxinfo/participant.rs, src/broadcast/participant.rs, src/errors.rs, src/keygen/mod.rs, src/keygen/participant.rs, src/participant.rs, src/presign/mod.rs, src/presign/participant.rs, src/protocol.rs, src/sign/interactive_sign/participant.rs, src/sign/non_interactive_sign/participant.rs
=> Consolidate definitions of Status into a single enum.

src/presign/round_three.rs
Closes #369 
I tried testing this but it involves immense amounts of mucking around with deserialized bits and trying to construct different inner types and I decided just rely on the documentation for `Scalar::from_repr` for confidence that this works.
=> add delta check #369

src/keygen/output.rs, src/presign/participant.rs, src/presign/record.rs, src/sign/non_interactive_sign/participant.rs, src/utils.rs, src/zkp/pilog.rs
=> 338 CurvePoint API

src/zkp/pifac.rs
=> 465 Fix Negative tests in PiFac

README.md, rust-toolchain.toml, src/auxinfo/mod.rs, src/presign/mod.rs, src/sign/interactive_sign/participant.rs, src/sign/non_interactive_sign/participant.rs
=> update rust version

README.md, rust-toolchain.toml, src/auxinfo/participant.rs, src/keygen/participant.rs, src/participant.rs, src/presign/participant.rs, src/protocol.rs
=> Bump Rust version to 1.76

src/protocol.rs
=> Add constructor for participant IDs.

src/presign/input.rs, src/presign/participant.rs
Issue https://github.com/boltlabs-inc/tss-ecdsa/issues/149 and https://github.com/boltlabs-inc/tss-ecdsa/issues/244
=> Add rid to the proof contexts in presign

src/protocol.rs
@becgabri @jwantz Please see my changes to the wording on the documentation and lmk if this agrees with what we talked about today. Thanks.
=> Update documentation of participant identifiers.
